ingress:
  domains:
  - ap-bom.zec.rocks

zebra:
  enabled: true
  initSnapshot:
    enabled: true

zcashd:
  enabled: false

lightwalletd:
  image:
    repository: emersonian/zcash-lwd
    tag: v0.4.17-cache1
    hash: bfd1dd2577bd9f163ae1274228246479c145d6237c34664735a34e376d6cf3c4

rpc:
  credentials:
    rpcUser: zeczeczec
    rpcPassword: REDACTED
