app = 'zecrocks-ap'
primary_region = 'sin'

[build]

[deploy]
  strategy = 'bluegreen'

[http_service]
  internal_port = 8080
  force_https = true
  min_machines_running = 1

  [http_service.concurrency]
    hard_limit = 2000
    soft_limit = 1500

  [http_service.tls_options]
    alpn = ['h2', 'http/1.1']
    versions = ['TLSv1.2', 'TLSv1.3']
    default_self_signed = false

  [http_service.http_options]
    h2_backend = true

  [[http_service.checks]]
    interval = '5s'
    timeout = '3s'
    grace_period = '5s'
    method = 'GET'
    path = '/'
    protocol = 'http'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
